language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: eHrof9LijVvENce3hT5jTJOCJKcWbeYBFLhpg7cRSkzTwa7oGxnwv2L5lgfbexZW55yIGIjpkiAavt7TIfe7PEYDzs+p4P/lRTYMqjP460+BdMbB407FgsSO5UZip2Rg3BhLLS44KA+J7zau2t3wBoqkcX/n7ues5diwBmV8OR7P7MplAMZ7ChpikxIVf6GiaXW2BwL9UdC8/Kfbm7lUXGJLJslaOFxE9JZRX0b9aGA9gDJ/W9Iac54RtSSdteXxwVkRTAjdyEXYrzjTSWMOrYURt/5IJ3t9eGR48yA+vWjpzcdZ588A9tXdWt8Zt7n2UcTW7ULVJeQX6DcUJ2DCRC9ZlVlhz6L/sHChshicQRkn/a7lN25F8Ig9J1d5cuAd3R8/l8HhP74h4p5Q4ZM2aSTunRrt9pXt9mdIiz9Iy45GqGW//Jq5intBqMvwFIpgPhPkqW5JbozRIh9mi6CXoh8yDjBI+g7X3jLarFFir1uRKtc7sahQjkBXuttXTYnOkxBT2/tLF+5KaIUt13tkdxL7Wr7QnG+chKf0b7CZA1pNxhHpvjKwr5a665P8BIMqPDFOMEhIggBsMW7TyrOhAATcqt0thLrZpziyA/bIS0p/LgQyixgiPFY/XtmFNWDRmPFZARG9ezGvtTVYjhkhWqUnesOozMjjC30fvKLYnCc=
  - secure: o/FdEiKf4kafx5Vak5L/RNhTCQ+AYrgGy06NmY0EQmHG7x+wP7hjRO2DlvYvxYPW2yCNCYMgvSSms1IXGpwdVCbX+QIV0Zl95NC35Vp9x4eLOsyzHnr60dvjBUEJBOqHJa9gC42ib+AE0C8OjlV+Fixi+mWJXH+j0ipnSmn//RxloaR9R3SoWvn7acM/KUoGO7gBNUlpJUi1SYdEY4czp1RTk7QJPXZ5KMb4C0GqlG19syxtrCrgFKHYAsNfTdBHj7avsGGnWJFUcu3LkK8HVW00fSfrm8yhkNyNGKgKxO5bI+L1heCLRo2rm1fZXLToEHAhUUVG4nSeq+2PRpqpUs6G3mi/3+tiIuFGqUxYU38n1fLOUInNib33RRPBpDbYdM0MWOON+vwxri7U3EDGkPasoJNQmWMe7WuMESR1oD7aFxlNR/jeNwKd/QxHR2ea1Bc9+PJb49KpDpbuvjMHRvqQm5tS8LW84Lrca3PNGE/OA4rsNnrqI1ia11ZmMZd4YRv42RnpFzFBMhutpQOP8mylh3goh0kUQeqX+ifKi7ht+roTHKAipHWIWXvSAbZuMTCA5qZ5wKkM/1V5CjAvPK+EXcYai51Tye9FwjXJzSDz1/mqNRmBwSH932Y37yOYFRn+eZsbHGZJFbba16C1RRAKeYVbG1Zv4xiNZJRqqwA=
  - secure: N9xLiWBH7CgglbQ595vSZQHw+IQzH0YYfKTKXX9HFvDfInldAzwAS9Qvh3zPI4T239dYiAQf++hOKFfLcaAiWwzvEyj1rKzX6vYi3XGpu9HzdW0ycg0cBR1Go+kQXn3hijINauus5+goUsHfRo7YEWDuGfQAnT4A7/pmvdex2uc/WqAKK6vLenofxMdrfSOaNkmmwpmyGwPY7aNLcffwZFAwO0rkgB8K664+RTVZ/6dLYOndgW/+fT6XEKajJA5ayPxZQCEXltu2ELQOFjrPAzWESPwPnJqgaFlT3LMhqodHYndvFReYbbVnfhsxHUo0aWJ6mvO79OibvXKV9+wrpBjeFukLE0HhQd9aIby9+L1pgxeIbx+8yLbbReUvre8ICCGbTGHiyK3e1zUHpq9OuYbOPHGUHpxpXbacNPAMrW/ksa6JpyxeSkHGpZxoQ5h09JixdTkf86Dion5xa8E1HOGolTPdYQpHUo3dwRj2UFMREZGM8lg8eIE6xnUoj/XQ+/oYLRHSKhwVl1WnSJ11QwEIytEgGG4TZaK8B2Qjbt77ZfFsllbIyrByCZ0/PtsntSXHkLjjqDrG8Vitf8TdjZjxSJ9RQX/AKOFALlicWHw7vd1ErXeXYGJx7nObO99QU+lsod8imrnEIMIliZlY16Q0zHFl9bd5JrgtJFD1s4M=
before_install:
- export TZ=Pacific/Noumea
install: mvn install -DSkipTests=true -Dmaven.javadoc.skip=true -DcreateChecksum=true
script:
- mvn versioneye:update test jacoco:report
after_success:
- mvn coveralls:report
before_deploy:
- export RELEASE_PKG_FILE=$(ls target/*.war)
- export RELEASE_PKG_MD5_FILE=$(ls target/*.war.md5)
- export RELEASE_PKG_SHA_FILE=$(ls target/*.war.sha1)
- echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE
  to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: IrGxAge3/NaUpCDBCmgsZC5iHUfzspig1SunObC7e+XkoboT+EpKCaHZ7ztaBMZYt8UUVJrL9q3MXLxGM3d2YxlI0Zv/jloLpTvegZNGuA1YvsyGjaBBMTEO9W7jC6/olqOJXNEi6o1ukk86ksGbfXz6g+s+80wZEgcKdThaE1usYlO2z14b03Esoh7+Bl6nMKr0diXm2P0ngFv7V+Ik7jTnLiR8o3ohErzfC3nR+BDdTF8kjMOwuuhvUrjOjx3Tldo5xYSzwoluOfe98o0P3/a1W7pfJnWWiRZjhlDs5ApxUFZepg/gvl1fAZA3rr9Eln8MoRjbWOPkjXJN+h5Wj3SYA3s40lmNHKtVVb3rq4hteFCptGNPxp9NyA2tO1CBqCz+gkFikNVsuFJ+dlj5jyvltRJBF2K9o00XApqRFFyfkiAJaftQHbBDxXBLyo6J25v2F3h9aNp2q9WeoHoQaqGi6jZuw5vJSx+CegiP6xwyiQH9W1yVNGXCKJgdA4zFvjhPZQLTfcQtRFK5aIfi9hJLYg8SuC4oApOORQEvsg2weZmSNvUsiIDFz9SFoikyLI+Vow3j5sKeUrxotdarnlrzUdNKmAs+dvHvx4FveZ2frR6BSzXIOHS7QCaZcJCxEy37+d+XcgiAlBGRZuRfK6YYkYJjEB8voyH0ruNpYKc=
  file:
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_PKG_MD5_FILE}"
  - "${RELEASE_PKG_SHA_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: DSI-Ville-Noumea/webapp-project-archetype
notifications:
  slack:
    secure: I6wtnbZNUfcqykGREcvtJrvnMYUba6nG1W/zgVQAxZ1AxTz2AJn6wKeVK6Be+0/Gkg01rJGxMBRqPJdbnqK41ccDnlt4QxssTCw5oP2MZdd5a+TTL/ex4/fV3MH6QWNS0UAyHBlh5PQHniSrBR3CzKkHfgBF6v82YOFIUg3OXustCPmcH8r7HSQcvb7eU2pFE/E+QPISaY8v9CFe6P79n521JjETBa3B4oOaS9TSWrNGTSPWU9efVY+IMPLS+I2kmOQ26m2ddKT5nsNAV8Mw21QSCloiM+gnkr0FYtmbb+Z0NIA8zN976iugPpHXpZ/RXot/0jleZb3gscpiVzHJRdAGfMjlsSTt8j8Z+rMKbGh8Cd4Y7I9YgrzyomNp+nhTZ9bP5F3EWRLLoki58cDN1k5OzxgXs8oB3C+Tm9fD4fggHnkzM88Dr9CBJEvAWEKYdMvA3N1jl9vtRL9F2u2YwFcM3/jVScPhiYLQa8z69ulJZqyLjwGh7dBltIuWCyJWVBz8zvLD1cmYu9gtP7R71cB3fu7H6Q+1/GeVkCCzeHQOqnQ/98g9BJM2feBsIvdZudfjGpBbMwfo75F+1p853zCD1XeDf3Mx3R7vDXtU1NJ8Twu6Z63xWog4OSHhTZnNDE7kZGWY+eakZK0WVafb8jWWNWZ+n0WiDRmxCxgPWX0=
