language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: EG400Jt87ueye7EGS4+7qjtGmvBviTnu0eFK/DXB2erlBRYHOGrHfH/qrFhDvzCALDFoYWKcal8uPleQ1+z42nX29I3iY/IgtgUpTZzy1bgzKtcfxW1Lr83VkgjhLjmDxuOyHo0dJ62wUEkdXe7JSCaEgOz7gE2Mmib89yol0tssNyE/WieAzYx168cgn3iIsk9RYaiovUAfCuSEqWTKJmSeJXblRqBazbbdyFM6utiY1P2d+MqLufeTwaehPBOI186n0/8l13sxDpJLzIwcGgc8h1PnzJpU0yhgHwudNd+sEug4ddS8Uf97xHk+TvCRHvg9Fmn9dTQ5MJO7A2ebX/nyDXoYdiCnCqnwqhGcwhm3Cz36DE6alMMh0mCn43/Vgk+KQAqmVDRudKDx5Ci9RHV3cMUAqlFN1yP1dQMDAzrMOW7/OnxfhCGp0tmirvFVtQUVegmAlNHQeeF+sAiutu16ZD7Mt66JXCe/54Oz+MeAVc+ah/8K2kDsXm1tKPrjSrTGwJLowWJTcLYIlptQuGxBfcKbxNJOzLKPKcFczU7n/ixqa1uQnRdtBR3L6ZKLvjq6BGK8q1HyjAkS7qdkW2M4vZ3/rtm6JxMTPof5OgbmIVnZd0grM0zN9TEMdCjDQIk5gbIjbIKoOUPiGIkXbgklwRI8Q/aFOkASEk5vGkA=
  - secure: w7xZ/2znkO0yOSt44SIL7/CQrQxKAukGGhWI7c8kWJIBo6MZD3xmBBacOMYyfAA6bgYHfXgcm58kMDSkBsRVBUG1aa+vJvbS4OsoVl2o0129V22HxqoGfhLCUtZTIQmg5CKtHbGd3lkISDPcPinFMjgrnunSP13l1iR6xq0sdIr2tIkbS8id8ZdWzMh3bPJjHZikkWpV4PZmyTCP/5dqdLCifdoqmhWNWVFcv8fWxPSlCaw3Pl9IxTyo1S1E3z0B5wRAPbkguAeK9N591bBVhMU9k2M0bQnQeRwGKeXC1KwgB6uQPYrtg6S8zVj/hbkBE5aAm0SVgobLprGWjXt8PkF0yMSUXxZHns8YKToTAVmKu/csEKWWydK0mTsXhvK6Ttu9NGV3WZTFSMgD+UJo6URQXofdOaQmdJicLeN8MYpBGlkb1I0tNSC5ieBE6x60SO/+49sJAFe+uldhM5krXQyPVUR4yUev76MwI6v2kR+1oH62e3HZEQXo9CXo0Iw2gzJfDfUQLxgu0UJeKCmvt10pjSr/D4HNdtoxuKNLWgFYfPT6v11mNzGCps5lOzC4Be6UxFawca54GQmMNe+HUxjTgVuW6MOlxqPEBoL/Gif3vyOeFHOVKVsOUFJO7rNHw6j9sbtpNxOqV24ZwDlubEh/866GKF324M0tZK/rq1k=
  - secure: pV8uLgIk0DwhyxNY5WbtXPRXherwtmC8e79DEOZetYztR3Z8DhVMn3j2k9h72NN8miJy7slwZO0whel9DdF/iiC0tsC+CEhVXajMA3oCbsHuOg3Yn1LOTeziu9M/t58CFapsJbmghkf1HmPLrCnzW27+X+suWY+hdAzSFUwtwXyvPh00M6WHmbWJMMqpE9YvSne1nwvJ5vI3RaZjeIBwI0IgVz7BknFGfS5JeN99G3rhGcYIntKs3XnPNlENQ3iGFWNfAsALMS6UgJVgjqt9ZqvUu39jVfUY1ZX7f542urS43v/RAQRQGbFGffd3IIstJzhN3ul89A8exGi8uXmSiD359xpaZdZ6LOaVw4+MaNqQmMc53rMW+bc4RAUSJglXXTLPURspoMpLsxoy1kzGSqK+rAiyNQ27PSD+EAokKSDWvsSKj01cb3YgzQ2ddjoQg1RXNSwrM5DDWKQ0CoG0EL0x0NMsixcTp+0SyQtuVgLpkDU3EfjEdktxCYrb5h7wW1MN21oFxf0kiVG6ym90Y4IGDd83zDwqwMux4SC9jGgc23PfZoK1a8KYoXY3o/dyXPkiaP8wY+A6qjfIgOi4MXlunwBjKrjgVYK75vGHRrUp5PUP69bnDeKecBL4LarXkxk7UHwKMVUVFZYGz7azXqKRCmxlw0c8IUEkf9QDqgw=
before_install:
- export TZ=Pacific/Noumea
install: mvn install -DSkipTests=true -Dmaven.javadoc.skip=true -DcreateChecksum=true
script:
- mvn versioneye:update test jacoco:report
after_success:
- mvn coveralls:report
before_deploy:
- export RELEASE_PKG_FILE=$(ls target/*.war)
- export RELEASE_PKG_MD5_FILE=$(ls target/*.war.md5)
- export RELEASE_PKG_SHA_FILE=$(ls target/*.war.sha1)
- echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE
  to GitHub releases"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: S/UajlA3kBg0XQr4wjJHWLUsLM70MxsYXQYgLl5kZjaoSrBYaByq8rFJNvWQXnTfnnmhL3NB9fGqCK5hybrwn2crpddiiOS7CuHo9Hd+LXtKRdFLxflNFCxIzq8zomCKU9jdv+BO7ykt6kfHiqr+Ku+Nz0ZIEbHM3XtxXYg+np7Nyjt7N2xxlwGmDtwb0td6leE+JdEa1GLAe/xcgkIFU+zcsd8tbe9XhU3ypKNgKqt370m9nQkWmMpdbtrtFGcxd/cxP0WiWujRwGphi5zN+z6GVBxPi1/nrjlgYOdYUC0+j7SD4X4BapvYLGpQq57xyU7M/l5yMaNd/3TCza5U0DS0yylxVwluAQgo2I6eq23fr2OCc5NaB494W548DHpGLiIqZ/YxqtM1tEYwu9kvxWlk5L/sQ6QWhlnrlib1/yC8v4Ce5puNS4TolXZoUvwams4ZEr7oXvTSQDJUoLVi6FmvYyD+UElDA5a2LdqgetRglyL8Cz9YHDcGZmZrV0FsAqrWBvOosoxBGJ8Vr6mbAtenaVkOXVxSDkno1nSu8266inYwQBwi6Xn15ZOTEYEd8Ik/rKTUCFGbjD5zxt/qaMiALbXN03dadwEBJuIYUdjIImalsMcJmqOJeiw134PNUv3dURBMWuqxMdWgIyvfB8kL0auw5h1x3L11cgeZM3M=
  file:
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_PKG_MD5_FILE}"
  - "${RELEASE_PKG_SHA_FILE}"
  on:
    tags: true
    repo: DSI-Ville-Noumea/webapp-project-archetype
